### ISSUE TITLE
Seems like a really cool project, but why put it on github if you're not going to include all the necessary files to build it?

### ISSUE THREAD

**Issue by BenGrasset** [genericptr/OpenGL-Tutorial#1]
Basically all of the units that start with "U" are absent from the repository... "UGeometry", "UArray", e.t.c.
You've also left out all of the shader and image assets! I certainly don't have a folder called "/Users/ryanjoseph/Desktop/Projects/Games/Minecraft/res" on my computer, haha.

**Comment by genericptr** [comment]
I seriously never thought even a single person would see this so I didn't bother. :) I fixed it now and could be built if you link SDL.

**Comment by BenGrasset** [comment]
Nice. Took me a little bit to get it to work on Windows but it was worth it. The cloud effects are awesome!

**Comment by genericptr** [comment]
That's interesting it works on Windows because on Mac I'm having some memory corruption issue in the Perlin noise generation (I think) which makes the terrain to be messed up. Something like an overflow error in the floating point types I'd guess.

Go check out of the rest of the ThinMatrix videos if you're learning OpenGL. I didn't get to water shaders, shadow mapping or post processing yet but I'll be picking away at that too.

**Comment by Akira1364** [comment]
Actually relatively experienced with OpenGL here... I just like checking out cool-looking projects, haha.

**Comment by BenGrasset** [comment]
Actually relatively experienced with OpenGL here... just like checking out cool-looking projects, haha.
